//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KomalliServer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class KomalliEntities : DbContext
    {
        public KomalliEntities()
            : base("name=KomalliEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<FoodOrder> FoodOrder { get; set; }
        public virtual DbSet<Ingredient> Ingredient { get; set; }
        public virtual DbSet<Logbook> Logbook { get; set; }
        public virtual DbSet<MenuCard> MenuCard { get; set; }
        public virtual DbSet<SetMenu> SetMenu { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Employee_Ingredient> Employee_Ingredient { get; set; }
        public virtual DbSet<FoodOrder_MenuCard> FoodOrder_MenuCard { get; set; }
        public virtual DbSet<FoodOrder_SetMenu> FoodOrder_SetMenu { get; set; }
    
        public virtual int ValidateUserLogin(string p_email, string p_password, ObjectParameter p_role, ObjectParameter p_available)
        {
            var p_emailParameter = p_email != null ?
                new ObjectParameter("p_email", p_email) :
                new ObjectParameter("p_email", typeof(string));
    
            var p_passwordParameter = p_password != null ?
                new ObjectParameter("p_password", p_password) :
                new ObjectParameter("p_password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ValidateUserLogin", p_emailParameter, p_passwordParameter, p_role, p_available);
        }
    }
}
