//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KomalliServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Ingredient
    {
        public string NoPersonalEmployee { get; set; }
        public string KeyIngredientIngredient { get; set; }
        public System.DateTime ReplenishmentDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Ingredient Ingredient { get; set; }
    }
}
