//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KomalliServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_FoodOrder
    {
        public string Employee_NoPersonal { get; set; }
        public string FoodOrder_IDFoodOrder { get; set; }
    
        public virtual FoodOrder FoodOrder { get; set; }
    }
}
