//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KomalliServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FoodOrder()
        {
            this.Employee_FoodOrder = new HashSet<Employee_FoodOrder>();
            this.FoodOrder_MenuCard = new HashSet<FoodOrder_MenuCard>();
            this.FoodOrder_SetMenu = new HashSet<FoodOrder_SetMenu>();
        }
    
        public string IDFoodOrder { get; set; }
        public string Status { get; set; }
        public string ClientName { get; set; }
        public System.DateTime Date { get; set; }
        public int Total { get; set; }
        public int NumberDishes { get; set; }
        public Nullable<int> Change { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_FoodOrder> Employee_FoodOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FoodOrder_MenuCard> FoodOrder_MenuCard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FoodOrder_SetMenu> FoodOrder_SetMenu { get; set; }
    }
}
