//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KomalliServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodOrder_SetMenu
    {
        public string IDFoodOrderFoodOrder { get; set; }
        public string KeySetMenuSetMenu { get; set; }
        public int Quantity { get; set; }
        public int SellingPrice { get; set; }
        public Nullable<int> UnitPrice { get; set; }
    
        public virtual FoodOrder FoodOrder { get; set; }
        public virtual SetMenu SetMenu { get; set; }
    }
}
