//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KomalliServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredient
    {
        public string KeyIngredient { get; set; }
        public string NameIngredient { get; set; }
        public string Quantity { get; set; }
        public string Measurement { get; set; }
        public string Barcode { get; set; }
        public Nullable<System.DateTime> ReplenishmentDate { get; set; }
    }
}
