//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KomalliServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logbook
    {
        public int IDCommentary { get; set; }
        public System.DateTime Date { get; set; }
        public string Commentary { get; set; }
        public string NoPersonalEmployee { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
