//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KomalliServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetMenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SetMenu()
        {
            this.FoodOrder_SetMenu = new HashSet<FoodOrder_SetMenu>();
        }
    
        public string KeySetMenu { get; set; }
        public System.DateTime Date { get; set; }
        public string Starter { get; set; }
        public string MainFood { get; set; }
        public string SideDish { get; set; }
        public string Salad { get; set; }
        public string Drink { get; set; }
        public int StudentPrice { get; set; }
        public int GeneralPrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FoodOrder_SetMenu> FoodOrder_SetMenu { get; set; }
    }
}
